config/routes.rb
Rails.application.routes.draw do

 devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root :to =>"public/homes#top"
  get "search" => "searchs#search"

  namespace :admin do
    get "/" => "homes#top"
    get "about" => "homes#about"
    #resources :sessions, only: [:new, :create, :destroy]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    get "/" => "homes#top"
    get "about" => "homes#about"
    get "customers/unsubscribe" => "customers#unsubscribe"
    get "customers/withdraw" => "customers#withdraw"
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    #get "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
    get "customers/my_page" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    #resources :registrations, only: [:new, :create]
    #resources :sessions, only: [:new, :create, :destroy]
    resources :items, only: [:index, :show]
    #resources :customers, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :index, :show, :create]
      patch :update_status
      post "orders/confirm" => "orders#confirm"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :customers do
     collection do
       get 'confirm_withdraw'
       patch 'withdraw'
     end
   end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  belongs_to :order, optional: true
  
  def add_tax_price
    (self.price * 1.10).round
  end

  def subtotal
    item.add_tax_price * amount
  end

  def update_total
    update(total: cart_items.sum(&:subtotal))
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  def customer_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end

  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  has_many :care_items, dependent: :destroy
  has_many :order_details
  has_many :orders, through: :order_details
  belongs_to :genre

  def add_tax_price
    (self.price * 1.10).round
  end

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/NO IMAGE.png')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      item_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :cart_items
  has_many :items, through: :cart_items
  has_many :order_details, dependent: :destroy

  enum status: {waiting_for_payment: 0, payment_confirmation: 1, making: 2, shipping_in_process: 3, shipping_completed: 4}
  enum payment_method: { credit_card: 0, transfer: 1 }

  def self.order_statuses_i18n
        order_statuses.keys.map do |status|
          [I18.t("enums.order.status.#{status}"), status]
        end.to_h
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item

    enum making_status: {unable_start: 0, waiting_for_production: 1, in_making: 2, making_completed: 3}
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers= Customer.all
    @customers= Customer.page(params[:page]).per(10)
  end

  def show
    @customer= Customer.find(params[:id])
  end

  def edit
    @customer= Customer.find(params[:id])
  end

  def update
    customer= Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path(customer)
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :postcode, :phone_number, :is_active)
  end
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).per(8)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @submit_label = '新規登録'
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "You have created item successfully."
    else
      render "new"
      @item = Item.new
      @submit_label = '新規登録'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @submit_label = '変更を保存'
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "You have updated item successfully."
    else
      render "edit"
      @item = Item.find(params[:id])
      @submit_label = '変更を保存'
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :item_image, :price, :is_active, :genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order= Order.find(params[:id])
    @order_details= @order.order_details
  end

  def update
    @order= Order.find(params[:id])
    @order.update(order_params)
    @order_details= @order.order_details

    if @order.status == "payment_confirmation"
      @order_details.each do |order_detail|
        order_detail.update(making_status:  "waiting_for_production")
        
      end
    end
    redirect_to admin_order_path
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container mt-4 mb-4">
  <div class="row">
    <div class="col-lg-1"></div>
    <h4><span style="background-color: rgb(220, 220, 220);"><%= @customer.full_name %>さんの会員情報編集</span></h4>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-10">
      <%= form_with model: [:admin, @customer] do |f| %>
        <table class="table table-borderless">
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td style="width: 15%">氏名</td>
            <td style="width: 20%"><%= f.text_field :last_name %></td>
            <td><%= f.text_field :first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= f.text_field :last_name_kana %></td>
            <td><%= f.text_field :first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= f.text_field :postal_code %></td>
            <td></td>
          </tr>
          <tr>
            <td>住所</td>
            <td colspan="2"><%= f.text_field :address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= f.text_field :telephone_number %></td>
            <td></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= f.text_field :email %></td>
            <td></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td>
              <%= f.radio_button :is_active, :true %>
              <%= f.label :is_active, "有効", {value: :true} %>
              <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active, "退会", {value: :false} %>
            </td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit "変更を保存", class:"btn btn-success" , data: { confirm: "本当に変更しますか？"} %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container mt-4 mb-4">
  <dic class="row">
    <div class= 'col-lg-1'></div>
    <div class="col-lg-3">
        <h4><span style="background-color: rgb(220, 220, 220);">会員一覧</span></h4>
    </div>
    <div class="col-lg-8"></div>
  </div>
    
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-9">
      <table class="table">
        <thead style="background-color: rgb(220, 220, 220);">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @customers.each do |customer| %>
          <tbody bgcolor="#ffffff">
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to customer.full_name, admin_customer_path(customer.id) %></td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_active %>
                  <p class="text-success"><strong>有効</strong></p>
                <% else %>
                  <p class="text-black-50"><strong>退会</strong></p>
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
  
      <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
          <%= paginate @customers %>
        </div>
        <div class="col-lg-4"></div>
      </div>
    </div>
    <div class="col-lg-1"></div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container mt-4 mb-4">
  <div class="row">
    <div class="col-lg-1"></div>
      <h4><span style="background-color: rgb(220, 220, 220);"><%= @customer.full_name %>さんの会員詳細</span></h4>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-10">
      <table>
        <tr>
          <th style="width: 40%">会員ID</th>
          </div>
          <td><%= @customer.id %></td>
        </tr>

        <tr>
          <th>氏名</th>
          <td><%= @customer.full_name %></td>
        </tr>

        <tr>
          <th>フリガナ</th>
          <td><%= @customer.full_name_kana %></td>
        </tr>

        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>

        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>

        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>

        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>

        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @customer.is_active %>
              <p class="text-success"><strong>有効</strong></p>
            <% else %>
              <p class="text-black-50"><strong>退会</strong></p>
            <% end %>
          </td>
        </tr>

        <tr>
          <th></th>
          <td><%= link_to"編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %> </td>
          <td><%= link_to"注文履歴一覧を見る",admin_path ,class: "btn btn-primary" %></td>

        </tr>
      </table>
    </div>
    </div>
  </div>
</div>