config/routes.rb
Rails.application.routes.draw do

 devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root :to =>"public/homes#top"
  get "search" => "searchs#search"

  namespace :admin do
    get "/" => "homes#top"
    get "about" => "homes#about"
    #resources :sessions, only: [:new, :create, :destroy]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    get "/" => "homes#top"
    get "about" => "homes#about"
    get "customers/unsubscribe" => "customers#unsubscribe"
    get "customers/withdraw" => "customers#withdraw"
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    #get "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
    get "customers/my_page" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    #resources :registrations, only: [:new, :create]
    #resources :sessions, only: [:new, :create, :destroy]
    resources :items, only: [:index, :show]
    #resources :customers, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :index, :show, :create]
      patch :update_status
      post "orders/confirm" => "orders#confirm"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :customers do
     collection do
       get 'confirm_withdraw'
       patch 'withdraw'
     end
   end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  belongs_to :order, optional: true
  
  def add_tax_price
    (self.price * 1.10).round
  end

  def subtotal
    item.add_tax_price * amount
  end

  def update_total
    update(total: cart_items.sum(&:subtotal))
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  def customer_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end

  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  has_many :care_items, dependent: :destroy
  has_many :order_details
  has_many :orders, through: :order_details
  belongs_to :genre

  def add_tax_price
    (self.price * 1.10).round
  end

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/NO IMAGE.png')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      item_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :cart_items
  has_many :items, through: :cart_items
  has_many :order_details, dependent: :destroy

  enum status: {waiting_for_payment: 0, payment_confirmation: 1, making: 2, shipping_in_process: 3, shipping_completed: 4}
  enum payment_method: { credit_card: 0, transfer: 1 }

  def self.order_statuses_i18n
        order_statuses.keys.map do |status|
          [I18.t("enums.order.status.#{status}"), status]
        end.to_h
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item

    enum making_status: {unable_start: 0, waiting_for_production: 1, in_making: 2, making_completed: 3}
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).per(8)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @submit_label = '新規登録'
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "You have created item successfully."
    else
      render "new"
      @item = Item.new
      @submit_label = '新規登録'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @submit_label = '変更を保存'
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "You have updated item successfully."
    else
      render "edit"
      @item = Item.find(params[:id])
      @submit_label = '変更を保存'
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :item_image, :price, :is_active, :genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order= Order.find(params[:id])
    @order_details= @order.order_details
  end

  def update
    @order= Order.find(params[:id])
    @order.update(order_params)
    @order_details= @order.order_details

    if @order.status == "payment_confirmation"
      @order_details.each do |order_detail|
        order_detail.update(making_status:  "waiting_for_production")
        
      end
    end
    redirect_to admin_order_path
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  before_action :authenticate_admin!
  
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class='container mt-4'>
  <div class='row'>
    <div class='col-lg-1'></div>
  <h4><span style="background-color: rgb(220, 220, 220);">ジャンル編集</span></h4>
  </div>

<div class="my-5">
<%= form_with model:@genre, url: admin_genre_path, method: :patch do |f| %>

<%= f.label :"ジャンル名" %>
<%= f.text_field :name %>
<%= f.submit '変更を保存', class: "btn btn-success" %>

<% end %>
</div>

</div>
</div>

app/views/admin/genres/index.html.erb
<div class='container mt-4'>
  <div class='row'>
    <div class='col-lg-1'></div>
  <h4><span style="background-color: rgb(220, 220, 220);">ジャンル一覧・追加</span></h4>
  </div>

<div class="my-4">
<%= form_with model:@genre, url: admin_genres_path, method: :post do |f| %>
<div class="row">
<div class="col-2"><%= f.label :"ジャンル名" %></div>
<div class="col-3"><%= f.text_field :name %></div>
<div class="col-2"><%= f.submit '新規登録', class: "btn btn-success" %></div>
</div>
<% end %>
</div>

<div class="row">
  <div class="col-4">
<table class="table">
  <thead>
    <tr class="bg-light">
      <th>
      ジャンル
      </th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <td class="text-center"><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>
</div>

app/views/admin/items/_form.html.erb
<!--tableタグの中にform_withを入れない-->
<%= form_with model: item, url: '/admin/items', method: :post do |f| %>
  <table class="table table-borderless">
    <tr>
      <th>商品画像</th>
      <td><%= f.file_field :item_image, accept: "image/*" %></td>
    </tr>
    <tr>
      <th>商品名</th>
      <td><%= f.text_field :name, placeholder: "商品名" %></td>
    </tr>
    <tr>
      <th>商品説明</th>
      <td><%= f.text_area :introduction, rows: '5', placeholder: "ここに説明文を記述します" %></td>
    </tr>
    <tr>
      <th>ジャンル</th>
      <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "-- 選択してください --" %></td>
    </tr>
    <tr>
      <th>税抜価格</th>
      <td><%= f.text_field :price, placeholder: "1000" %>円</td>
    </tr>
    <tr>
      <th>販売ステータス</th>
      <td><%= f.radio_button :is_active, "true" %>販売中　<%= f.radio_button :is_active, "false" %>販売停止</td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit submit_label, class: "btn btn-success" %></td>
    </tr>
  </table>
<% end %>

app/views/admin/items/edit.html.erb
<style>
  .box select{
    width: 270px;
  }
</style>


<div class="container mt-4 mb-4">
    <div class="row">
        <div class='col-lg-1'></div>
            <h4><span style="background-color: rgb(220, 220, 220);">商品編集</span></h4>
    </div>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <!--tableタグの中にform_withを入れない-->
            <%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>
              <table class="table table-borderless">
                <tr>
                  <th>商品画像</th>
                  <td><%= f.file_field :item_image, accept: "image/*" %></td>
                </tr>
                <tr>
                  <th>商品名</th>
                  <td><%= f.text_field :name, size: 30, placeholder: "商品名" %></td>
                </tr>
                <tr>
                  <th>商品説明</th>
                  <td><%= f.text_area :introduction, rows: 5, cols: 29, placeholder: "ここに説明文を記述します" %></td>
                </tr>
                <tr>
                  <th>ジャンル</th>
                  <td class="box select"><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "-- 選択してください --" %></td>
                </tr>
                <tr>
                  <th>税抜価格</th>
                  <td><%= f.text_field :price, size: 30, placeholder: "1000" %>円</td>
                </tr>
                <tr>
                  <th>販売ステータス</th>
                  <td><%= f.radio_button :is_active, "true" %>販売中　<%= f.radio_button :is_active, "false" %>販売停止</td>
                </tr>
                <tr>
                  <td></td>
                  <td><%= f.submit @submit_label, class: "btn btn-success w-50" %></td>
                </tr>
              </table>
            <% end %>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

app/views/admin/items/index.html.erb
<div class="container mt-4 mb-4">
    <div class="row">
      <div class='col-lg-1'></div>
      <div class="col-lg-3">
        <h4><span style="background-color: rgb(220, 220, 220);">商品一覧</span></h4>
      </div>
      <div class="col-lg-6"></div>
      <div class="col-lg-1">
        <%= link_to "＋", new_admin_item_path, class: "btn btn-outline-secondary rounded-circle p-1", style: "width:2rem;height:2rem;" %>
      </div>
      <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
          <table class='table' >
            <thead style="background-color: rgb(220, 220, 220);">
              <tr>
                <th>商品ID</th>
                <th>商品名</th>
                <th>税抜価格</th>
                <th>ジャンル</th>
                <th>ステータス</th>
              </tr>
            </thead>
            <tbody bgcolor="#ffffff">
              <% @items.each do |item| %>
                <tr>
                  <td><%= item.id %></td>
                  <td><%= link_to item.name, admin_item_path(item) %></td>
                  <td><%= number_with_delimiter(item.price, delimiter: ',') %></td>
                  <td><%= item.genre.name %></td>
                  <td>
                    <% if item.is_active %>
                      <p class="text-success"><strong>販売中</strong></p>
                    <% else %>
                      <p class="text-black-50"><strong>販売停止中</strong></p>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="row">
            <div class="col-lg-4"></div>
            <div class="col-lg-4">
              <%= paginate @items %>
            </div>
            <div class="col-lg-4"></div>
          </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
</div>

app/views/admin/items/new.html.erb
<style>
  .box select{
    width: 270px;
  }
</style>


<div class="container mt-4 mb-4">
    <div class="row">
        <div class='col-lg-1'></div>
            <h4><span style="background-color: rgb(220, 220, 220);">商品新規登録</span></h4>
    </div>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <!--tableタグの中にform_withを入れない-->
            <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
              <table class="table table-borderless">
                <tr>
                  <th>商品画像</th>
                  <td><%= f.file_field :item_image, accept: "image/*" %></td>
                </tr>
                <tr>
                  <th>商品名</th>
                  <td><%= f.text_field :name, size: 30, placeholder: "商品名" %></td>
                </tr>
                <tr>
                  <th>商品説明</th>
                  <td><%= f.text_area :introduction, rows: 5, cols: 29, placeholder: "ここに説明文を記述します" %></td>
                </tr>
                <tr>
                  <th>ジャンル</th>
                  <td class="box select"><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "-- 選択してください --" %></td>
                </tr>
                <tr>
                  <th>税抜価格</th>
                  <td><%= f.text_field :price, size: 30, placeholder: "1000" %>円</td>
                </tr>
                <tr>
                  <th>販売ステータス</th>
                  <td><%= f.radio_button :is_active, "true" %>販売中　<%= f.radio_button :is_active, "false" %>販売停止</td>
                </tr>
                <tr>
                  <td></td>
                    <td><%= f.submit @submit_label, class: "btn btn-success w-50" %></td>
                </tr>
              </table>
            <% end %>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

app/views/admin/items/show.html.erb
<div class="container mt-4 mb-4">
    <div class="row">
        <div class='col-lg-1'></div>
            <h4><span style="background-color: rgb(220, 220, 220);">商品詳細</span></h4>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <%= image_tag @item.get_item_image(230,230) %>
        </div>
        <div class="col-lg-6">
            <table class="table table-borderless">
                <tr>
                    <th style="width: 28%">商品名</th>
                    <td><%= @item.name %></td>
                </tr>
                <tr>
                    <th>商品説明</th>
                    <td><%= @item.introduction %></td>
                </tr>
                <tr>
                    <th>ジャンル</th>
                    <td><%= @item.genre.name %></td>
                </tr>
                <tr>
                    <th>税込価格<br>(税抜価格)</th>
                    <td><%= number_with_delimiter(@item.add_tax_price, delimiter: ',') %>(<%= number_with_delimiter(@item.price, delimiter: ',') %>)円</td>
                </tr>
                <tr>
                    <th>販売ステータス</th>
                    <td>
                        <% if @item.is_active %>
                          <p class="text-success"><strong>販売中</strong></p>
                        <% else %>
                          <p class="text-black-50"><strong>販売停止中</strong></p>
                        <% end %>
                    </td>
                </tr>
            </table>
            <div class="row">
                <div class="col-lg-3"></div>
                <div class="col-lg-6">
                    <%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-sm btn-success w-50" %>
                </div>
                <div class="col-lg-3"></div>
            </div>
        </div>
        <div class="col-lg-2"></div>
    </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container mt-4 mb-4">
  <div class="row">
    <div class="col-lg-1"></div>
    <h4><span style="background-color: rgb(220, 220, 220);">注文履歴詳細</span></h4>
  </div>

  <div class="row mt-1">
    <div class="col-lg-8">
      <table>
        <tr>
          <th style="width:150px">購入者</th>
          <td><%= @order.customer.full_name %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <th></th>
          <td><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model:@order, url:admin_order_path, local: true do |f| %>
              <%= f.select :status, Order.statuses.keys.map { |k| [I18n.t("enums.order.status.#{k}"), k] } %>
              　<%#全角スペース%>
              <%= f.submit "更新", class: 'btn btn-success' %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-lg-8">
    <table>
      <thead style="background-color: rgb(220, 220, 220);">
        <tr>
          <th style="width: 35%">商品名</th>
          <th style="width: 20%">単価（税込）</th>
          <th style="width: 10%">数量</th>
          <th style="width: 10%">小計</th>
          <th style="width: 20%">製作ステータス</th>
          <th style="width: 15%"></th>
        </tr>
      </thead>

      <% @order_details.each do |order_detail| %>
      <tbody>
        <tr>
          <td style="height: 10px"><%= order_detail.item.name %></td>
          <td><%= (order_detail.price.floor*1.1).floor.to_s(:delimited) %></td>
          <td><%= order_detail.amount %></td>
          <td><%= ((order_detail.price * order_detail.amount*1.1).floor).to_s(:delimited) %></td>
          <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: true do |f| %>
            <td>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
            </td>
            <td>
              <%= f.submit "更新", class: 'btn btn-success' %>
            </td>
          <% end %>
        </tr>
      </tbody>
      <% end %>
    </table class="table">
    </div>
    <div class="col-lg-1"></div>
    <div class="col-lg-3">
      <table>
        <tr>
          <th><strong>商品合計</strong></th>
          <td><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %>円</td>
        <tr>
          <th><strong>送料</strong></th>
          <td><%= @order.shipping_cost %>円</td>
        </tr>
        <tr>
          <th><strong>請求金額合計</strong></th>
          <td><%= @order.total_payment.to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>