config/routes.rb
Rails.application.routes.draw do

 devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root :to =>"public/homes#top"
  get "search" => "searchs#search"

  namespace :admin do
    get "/" => "homes#top"
    get "about" => "homes#about"
    #resources :sessions, only: [:new, :create, :destroy]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    get "/" => "homes#top"
    get "about" => "homes#about"
    get "customers/unsubscribe" => "customers#unsubscribe"
    get "customers/withdraw" => "customers#withdraw"
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    #get "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
    get "customers/my_page" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    #resources :registrations, only: [:new, :create]
    #resources :sessions, only: [:new, :create, :destroy]
    resources :items, only: [:index, :show]
    #resources :customers, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :index, :show, :create]
      patch :update_status
      post "orders/confirm" => "orders#confirm"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :customers do
     collection do
       get 'confirm_withdraw'
       patch 'withdraw'
     end
   end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  belongs_to :order, optional: true
  
  def add_tax_price
    (self.price * 1.10).round
  end

  def subtotal
    item.add_tax_price * amount
  end

  def update_total
    update(total: cart_items.sum(&:subtotal))
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  def customer_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end

  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  has_many :care_items, dependent: :destroy
  has_many :order_details
  has_many :orders, through: :order_details
  belongs_to :genre

  def add_tax_price
    (self.price * 1.10).round
  end

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/NO IMAGE.png')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      item_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :cart_items
  has_many :items, through: :cart_items
  has_many :order_details, dependent: :destroy

  enum status: {waiting_for_payment: 0, payment_confirmation: 1, making: 2, shipping_in_process: 3, shipping_completed: 4}
  enum payment_method: { credit_card: 0, transfer: 1 }

  def self.order_statuses_i18n
        order_statuses.keys.map do |status|
          [I18.t("enums.order.status.#{status}"), status]
        end.to_h
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item

    enum making_status: {unable_start: 0, waiting_for_production: 1, in_making: 2, making_completed: 3}
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).per(8)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @submit_label = '新規登録'
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "You have created item successfully."
    else
      render "new"
      @item = Item.new
      @submit_label = '新規登録'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @submit_label = '変更を保存'
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "You have updated item successfully."
    else
      render "edit"
      @item = Item.find(params[:id])
      @submit_label = '変更を保存'
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :item_image, :price, :is_active, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="border-top border-dark bg-light">
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="border-bottom border-dark bg-light">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag('naganocake.png') %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <% if admin_signed_in? %>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%= link_to admin_items_path,class: 'nav-link text-dark' do %>
              商品一覧
            <% end %>
          </li>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%= link_to admin_customers_path,class: 'nav-link text-dark' do %>
              会員一覧
            <% end %>
          </li>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%= link_to admin_path,class: 'nav-link text-dark' do %>
              注文履歴一覧
            <% end %>
          </li>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%=  link_to admin_genres_path ,class: 'nav-link text-dark' do %>
              ジャンル一覧
            <% end %>
          </li>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-dark' do %>
              ログアウト
            <% end %>
          </li>

        <% elsif customer_signed_in? %>
        <div class="mt-3 mr-5 text-dark">ようこそ、<%= current_customer.last_name %>さん!</div>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%= link_to customers_my_page_path,class: 'nav-link text-dark' do %>
              マイページ
            <% end %>
          </li>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%= link_to items_path,class: 'nav-link text-dark' do %>
              商品一覧
            <% end %>
          </li>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%= link_to cart_items_path,class: 'nav-link text-dark' do %>
              カート
            <% end %>
          </li>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-dark' do %>
              ログアウト
            <% end %>
          </li>

        <% else %>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%= link_to about_path,class: 'nav-link text-dark' do %>
              About
            <% end %>
          </li>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%= link_to items_path ,class: 'nav-link text-dark' do %>
              商品一覧
            <% end %>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%= link_to new_customer_registration_path,class: 'nav-link text-dark' do %>
              新規登録
            <% end %>
          </li>
          <li type="button" class="btn btn-outline-secondary m-2">
            <%= link_to new_customer_session_path ,class: 'nav-link text-dark' do %>
              ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
    <div class="search_form pb-2 mr-5">
      <%= form_with url: search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word %>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NgnCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render '/layouts/header' %>
  <body>
    <%= yield %>
  </body>
  <div class="fixed-bottom">
    <%= render '/layouts/footer' %>
  </div>
</html>